// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"bg-gray-900\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12\"><div class=\"grid md:grid-cols-4 gap-8\"><div><h4 class=\"text-white font-semibold mb-4 text-lg\">About</h4><ul class=\"space-y-3\"><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">Company</a></li><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">Team</a></li><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">Careers</a></li></ul></div><div><h4 class=\"text-white font-semibold mb-4 text-lg\">Resources</h4><ul class=\"space-y-3\"><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">Documentation</a></li><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">Help Center</a></li><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">Blog</a></li></ul></div><div><h4 class=\"text-white font-semibold mb-4 text-lg\">Legal</h4><ul class=\"space-y-3\"><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">Privacy</a></li><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">Terms</a></li><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">Security</a></li></ul></div><div><h4 class=\"text-white font-semibold mb-4 text-lg\">Connect</h4><ul class=\"space-y-3\"><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">Twitter</a></li><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">LinkedIn</a></li><li><a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">GitHub</a></li></ul></div></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
